openapi: 3.0.3
info:
  version: 1.0.0
  title: Marketplace API
  description: Description coming soon
servers:
  - url: http://localhost:3001
    description: Local server
  - url: https://hosted.on.herokuapp.com
    description: Cloud server
tags:
  - name: products
    description: Endpoints related to products
  - name: reviews
    description: Endpoints related to reviews
  - name: services
    description: Endpoints related to services
paths:
  /products:
    get:
      tags:
        - products
      summary: Returns an array of all products
      responses:
        "200":
          description: An array of all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: Not found error sent to the user
    post:
      tags:
        - products
      summary: Adds a new product
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/New Product"
      responses:
        "200":
          description: Successful post
          content:
            text/html:
              schema:
                type: string
                example: "New product successfully added"
        "400":
          description: Detailed error message provided

        "500":
          description: Generic server error message provided

  /products/{id}:
    get:
      tags:
        - products
      summary: Returns a single book
      description: Extendend description of GET /books/:asin route
      parameters:
        - in: path
          name: id
          schema:
            type: string
          description: "The ID of the product to fetch."
          required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "400":
          description: Detailed error messaged provided

        "404":
          description: Not Found
          content:
            text/html:
              schema:
                type: string
        "500":
          description: Generic Server Error
          content:
            text/html:
              schema:
                type: string
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        brand:
          type: string
        price:
          type: number
        category:
          type: string
        reviews:
          type: array
          items:
            type: object
        _id:
          type: string
        _createdAt:
          type: string
        _updatedAt:
          type: string
        image:
          type: string
    New Product:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        brand:
          type: string
        price:
          type: number
        category:
          type: string
    Error Message:
      type:
